version: "2"

services:
  data:
    image: busybox
    volumes:
      - .:/var/www/app

  nginx:
    image: vv-api-nginx
    ports:
      - "80:80"
    links:
      - fpm
    volumes_from:
      - data

  fpm:
    image: vv-api-fpm
    volumes_from:
      - data

  artisan:
    image: vv-api-fpm
    volumes:
      - .:/var/www/app
    entrypoint: "./artisan"
    working_dir: /var/www/app
