version: "2"

services:
  data:
    image: busybox
    volumes:
      - .:/var/www/app
  web:
    image: vv-api
    ports:
      - "80:80"
    volumes_from:
      - data

  artisan:
    image: vv-api
    volumes:
      - .:/var/www/app
    entrypoint: "./artisan"
    working_dir: /var/www/app